# Generated by Django 3.1.2 on 2020-10-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemTitle', models.CharField(max_length=100, verbose_name='problemTitle')),
                ('problemTime', models.DateTimeField(auto_now_add=True, verbose_name='problemTime')),
                ('problemAuthor', models.CharField(max_length=50, verbose_name='problemAuthor')),
                ('problemContent', models.TextField(verbose_name='problemContent')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyTitle', models.CharField(max_length=50, verbose_name='replyTitle')),
                ('replyTime', models.DateTimeField(auto_now_add=True, verbose_name='replyTime')),
                ('replyAuthor', models.CharField(max_length=50, verbose_name='replyAuthor')),
                ('replyText', models.TextField(verbose_name='replyText')),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problemsmodel')),
            ],
        ),
    ]
