# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\2020Hackerton\Your_Problem_10_29_move\QtApplicationPart\ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 787)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK KR Regular")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(253, 240, 237);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("QLabel {\n"
"    font: 18pt \"Tmoney RoundWind\";\n"
"    color: rgb(138, 137, 212);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius : 10px;\n"
"    border: 2px solid;\n"
"    border-color: rgb(127, 127, 127);\n"
"    font: 11pt \"SpoqaHanSans-Regular\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border-radius : 10px;\n"
"    font: 10pt \"SpoqaHanSans-Regular\";\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"}\n"
"\n"
"QEditText {\n"
"    font: 81 16pt \"Tmoney RoundWind\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    font: 81 16pt \"Tmoney RoundWind\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tmoney RoundWind")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font: 75 50pt \"Tmoney RoundWind\";")
        self.titleLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionLabel.sizePolicy().hasHeightForWidth())
        self.descriptionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tmoney RoundWind")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setStyleSheet("color: rgb(208, 164, 114);")
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_2.addWidget(self.descriptionLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.goToPage1Btn = QtWidgets.QPushButton(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goToPage1Btn.sizePolicy().hasHeightForWidth())
        self.goToPage1Btn.setSizePolicy(sizePolicy)
        self.goToPage1Btn.setMinimumSize(QtCore.QSize(320, 40))
        font = QtGui.QFont()
        font.setFamily("SpoqaHanSans-Regular")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.goToPage1Btn.setFont(font)
        self.goToPage1Btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.goToPage1Btn.setFlat(False)
        self.goToPage1Btn.setObjectName("goToPage1Btn")
        self.verticalLayout_2.addWidget(self.goToPage1Btn, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.nameLabel = QtWidgets.QLabel(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tmoney RoundWind")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: rgb(208, 164, 114);")
        self.nameLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.nameLineEdit = QtWidgets.QLineEdit(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(320, 50))
        self.nameLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit, 0, QtCore.Qt.AlignHCenter)
        self.goToPage2Btn = QtWidgets.QPushButton(self.page1)
        self.goToPage2Btn.setMinimumSize(QtCore.QSize(320, 40))
        self.goToPage2Btn.setStyleSheet("")
        self.goToPage2Btn.setObjectName("goToPage2Btn")
        self.verticalLayout.addWidget(self.goToPage2Btn, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.problemContentTextEdit = QtWidgets.QTextEdit(self.page2)
        self.problemContentTextEdit.setStyleSheet("font: 14pt \"티머니 둥근바람 Regular\";\n"
"background-color: rgb(255, 255, 255);")
        self.problemContentTextEdit.setTabChangesFocus(True)
        self.problemContentTextEdit.setPlaceholderText("이곳에 고민을 적어주세요")
        self.problemContentTextEdit.setObjectName("problemContentTextEdit")
        self.gridLayout_2.addWidget(self.problemContentTextEdit, 3, 0, 1, 2)
        self.backToPage1Btn = QtWidgets.QPushButton(self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backToPage1Btn.sizePolicy().hasHeightForWidth())
        self.backToPage1Btn.setSizePolicy(sizePolicy)
        self.backToPage1Btn.setMinimumSize(QtCore.QSize(150, 40))
        self.backToPage1Btn.setObjectName("backToPage1Btn")
        self.gridLayout_2.addWidget(self.backToPage1Btn, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.problemLabel2 = QtWidgets.QLabel(self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.problemLabel2.sizePolicy().hasHeightForWidth())
        self.problemLabel2.setSizePolicy(sizePolicy)
        self.problemLabel2.setAutoFillBackground(False)
        self.problemLabel2.setStyleSheet("")
        self.problemLabel2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.problemLabel2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.problemLabel2.setTextFormat(QtCore.Qt.RichText)
        self.problemLabel2.setWordWrap(True)
        self.problemLabel2.setObjectName("problemLabel2")
        self.gridLayout_2.addWidget(self.problemLabel2, 1, 0, 1, 2)
        self.problemLabel1 = QtWidgets.QLabel(self.page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.problemLabel1.sizePolicy().hasHeightForWidth())
        self.problemLabel1.setSizePolicy(sizePolicy)
        self.problemLabel1.setStyleSheet("font: 26pt \"Tmoney RoundWind\";")
        self.problemLabel1.setTextFormat(QtCore.Qt.PlainText)
        self.problemLabel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.problemLabel1.setWordWrap(True)
        self.problemLabel1.setObjectName("problemLabel1")
        self.gridLayout_2.addWidget(self.problemLabel1, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.postProblemBtn = QtWidgets.QPushButton(self.page2)
        self.postProblemBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.postProblemBtn.setObjectName("postProblemBtn")
        self.gridLayout_2.addWidget(self.postProblemBtn, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.problemTitleTextEdit = QtWidgets.QTextEdit(self.page2)
        self.problemTitleTextEdit.setStyleSheet("font: 16pt \"티머니 둥근바람 Regular\";\n"
"background-color: rgb(255, 255, 255);")
        self.problemTitleTextEdit.setTabChangesFocus(True)
        self.problemTitleTextEdit.setPlaceholderText("고민의 제목을 입력해주세요")
        self.problemTitleTextEdit.setObjectName("problemTitleTextEdit")
        self.gridLayout_2.addWidget(self.problemTitleTextEdit, 2, 0, 1, 2)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(1, 5)
        self.gridLayout_2.setRowStretch(2, 10)
        self.gridLayout_2.setRowStretch(3, 60)
        self.gridLayout_2.setRowStretch(4, 5)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout = QtWidgets.QGridLayout(self.page3)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.page3)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.problemListView = QtWidgets.QListView(self.page3)
        self.problemListView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.problemListView.setObjectName("problemListView")
        self.gridLayout.addWidget(self.problemListView, 1, 0, 1, 1)
        self.goToPage4Btn = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goToPage4Btn.sizePolicy().hasHeightForWidth())
        self.goToPage4Btn.setSizePolicy(sizePolicy)
        self.goToPage4Btn.setMinimumSize(QtCore.QSize(220, 40))
        self.goToPage4Btn.setObjectName("goToPage4Btn")
        self.gridLayout.addWidget(self.goToPage4Btn, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 95)
        self.gridLayout.setRowStretch(2, 5)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page4)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.replyContentTextEdit = QtWidgets.QTextEdit(self.page4)
        self.replyContentTextEdit.setStyleSheet("font: 16pt \"티머니 둥근바람 Regular\";\n"
"background-color: rgb(255, 255, 255);")
        self.replyContentTextEdit.setTabChangesFocus(True)
        self.replyContentTextEdit.setObjectName("replyContentTextEdit")
        self.gridLayout_3.addWidget(self.replyContentTextEdit, 2, 1, 1, 1)
        self.backToPage3Btn = QtWidgets.QPushButton(self.page4)
        self.backToPage3Btn.setMinimumSize(QtCore.QSize(150, 40))
        self.backToPage3Btn.setObjectName("backToPage3Btn")
        self.gridLayout_3.addWidget(self.backToPage3Btn, 3, 0, 1, 1)
        self.postReplyBtn = QtWidgets.QPushButton(self.page4)
        self.postReplyBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.postReplyBtn.setObjectName("postReplyBtn")
        self.gridLayout_3.addWidget(self.postReplyBtn, 3, 1, 1, 1)
        self.replyTitleTextEdit = QtWidgets.QTextEdit(self.page4)
        self.replyTitleTextEdit.setStyleSheet("font: 16pt \"티머니 둥근바람 Regular\";\n"
"background-color: rgb(255, 255, 255);")
        self.replyTitleTextEdit.setTabChangesFocus(True)
        self.replyTitleTextEdit.setObjectName("replyTitleTextEdit")
        self.gridLayout_3.addWidget(self.replyTitleTextEdit, 1, 1, 1, 1)
        self.otherProblemTextBrower = QtWidgets.QTextBrowser(self.page4)
        self.otherProblemTextBrower.setObjectName("otherProblemTextBrower")
        self.gridLayout_3.addWidget(self.otherProblemTextBrower, 1, 0, 2, 1)
        self.replyPostLabel = QtWidgets.QLabel(self.page4)
        self.replyPostLabel.setObjectName("replyPostLabel")
        self.gridLayout_3.addWidget(self.replyPostLabel, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 50)
        self.gridLayout_3.setColumnStretch(1, 50)
        self.gridLayout_3.setRowStretch(0, 5)
        self.gridLayout_3.setRowStretch(1, 5)
        self.gridLayout_3.setRowStretch(2, 90)
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page5)
        self.gridLayout_5.setVerticalSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fifthLabel1 = QtWidgets.QLabel(self.page5)
        self.fifthLabel1.setStyleSheet("font: 75 30pt \"Tmoney RoundWind\";")
        self.fifthLabel1.setObjectName("fifthLabel1")
        self.gridLayout_5.addWidget(self.fifthLabel1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.fifthLabel2 = QtWidgets.QLabel(self.page5)
        self.fifthLabel2.setObjectName("fifthLabel2")
        self.gridLayout_5.addWidget(self.fifthLabel2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setObjectName("page6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page6)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.myProblemTextBrowser = QtWidgets.QTextBrowser(self.page6)
        self.myProblemTextBrowser.setTabChangesFocus(True)
        self.myProblemTextBrowser.setObjectName("myProblemTextBrowser")
        self.gridLayout_6.addWidget(self.myProblemTextBrowser, 1, 0, 1, 1)
        self.replyLabel = QtWidgets.QLabel(self.page6)
        self.replyLabel.setObjectName("replyLabel")
        self.gridLayout_6.addWidget(self.replyLabel, 0, 0, 1, 1)
        self.otherReplyTextBrowser = QtWidgets.QTextBrowser(self.page6)
        self.otherReplyTextBrowser.setTabChangesFocus(True)
        self.otherReplyTextBrowser.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.otherReplyTextBrowser.setObjectName("otherReplyTextBrowser")
        self.gridLayout_6.addWidget(self.otherReplyTextBrowser, 1, 1, 1, 1)
        self.gridLayout_6.setRowStretch(0, 5)
        self.gridLayout_6.setRowStretch(1, 90)
        self.stackedWidget.addWidget(self.page6)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.consoleLabel = QtWidgets.QLabel(self.centralwidget)
        self.consoleLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.consoleLabel.setStyleSheet("QLabel {\n"
"    font: 15pt \"NEXON Lv1 Gothic\";\n"
"    color: rgb(138, 137, 212);\n"
"}")
        self.consoleLabel.setText("")
        self.consoleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.consoleLabel.setObjectName("consoleLabel")
        self.verticalLayout_3.addWidget(self.consoleLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.nameLineEdit.returnPressed.connect(self.goToPage2Btn.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "너의 고민은"))
        self.descriptionLabel.setText(_translate("MainWindow", "당신의 고민을 다른 사람에게 얘기해줄래요?"))
        self.goToPage1Btn.setText(_translate("MainWindow", "다음"))
        self.nameLabel.setText(_translate("MainWindow", "다른 사람에게 불리고 싶은 이름을 적어주세요!"))
        self.goToPage2Btn.setText(_translate("MainWindow", "다음"))
        self.backToPage1Btn.setText(_translate("MainWindow", "뒤로가기"))
        self.problemLabel2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">다른 사람이 이 고민을 보고 따뜻한 위로의 말이나 조언을 써서 답장을 보낼겁니다!</span></p></body></html>"))
        self.problemLabel1.setText(_translate("MainWindow", "당신의 고민을 적어주세요!"))
        self.postProblemBtn.setText(_translate("MainWindow", "보내기"))
        self.label.setText(_translate("MainWindow", "답장을 보낼 다른 사람의 고민을 선택해주세요!"))
        self.goToPage4Btn.setText(_translate("MainWindow", "선택하고 다음으로 가기"))
        self.replyContentTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'티머니 둥근바람 Regular\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.replyContentTextEdit.setPlaceholderText(_translate("MainWindow", "이곳에 내용을 입력"))
        self.backToPage3Btn.setText(_translate("MainWindow", "뒤로가기"))
        self.postReplyBtn.setText(_translate("MainWindow", "답장 전송하기"))
        self.replyTitleTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'티머니 둥근바람 Regular\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.replyTitleTextEdit.setPlaceholderText(_translate("MainWindow", "이곳에 제목을 입력"))
        self.otherProblemTextBrower.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tmoney RoundWind\'; font-size:16pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.otherProblemTextBrower.setPlaceholderText(_translate("MainWindow", "이곳에 다른 사람의 고민이 있을거임"))
        self.replyPostLabel.setText(_translate("MainWindow", "다른 사람의 고민에 따뜻한 답장을 보내주세요!"))
        self.fifthLabel1.setText(_translate("MainWindow", "정말 마음 따뜻해지는 답장이군요!"))
        self.fifthLabel2.setText(_translate("MainWindow", "님의 답장도 곧 돌아올거에요... 편안히 기다려주세요"))
        self.myProblemTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tmoney RoundWind\'; font-size:16pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.myProblemTextBrowser.setPlaceholderText(_translate("MainWindow", "여기에 나의 고민이 있음"))
        self.replyLabel.setText(_translate("MainWindow", "답장이 도착했습니다!"))
        self.otherReplyTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tmoney RoundWind\'; font-size:16pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.otherReplyTextBrowser.setPlaceholderText(_translate("MainWindow", "여기에 답장이 있음"))
import resources_rc
